### ISSUE TITLE
Having a Tagless Final version of the API

### ISSUE THREAD

**Issue by nhenin** [blockfrost/blockfrost-haskell#10]
Hi, It's quite difficult to compose logic with a rigid datatype like : 
```haskell 
type ClientConfig = (ClientEnv, Project)
type BlockfrostClient =
  ExceptT BlockfrostError
    (ReaderT ClientConfig IO)
```
I would have expected using the API that way : 

```haskell 
getTx :: BlockfrostClient m => TxHash -> m Transaction
-- vs
getTx :: TxHash -> BlockfrostClient Transaction
```

And be able to compose my logic that way : 

```haskell
myOwnLogic ::  (BlockfrostClient m , OtherClient m ) => Hash -> m (Tx,Tx')
myOwnLogic  hash = do 
  tx <- getTx hash
  tx' <- getTxFromOtherClient hash
  return (tx,tx')
```
what do you think ?

**Comment by sorki** [comment]
Hi, sounds good to me but to be honest, I'm not sure how to convert it to tagless final right away. If you have good example I can take a look at or draft a solution here it would help a lot.

Regarding breaking the API - I don't think there are that many users of this library so it should be fine.

**Comment by sorki** [comment]
I've remembered about https://jproyo.github.io/posts/2019-03-17-tagless-final-haskell.html and it makes sense, having a type`class BlockfrostClient` (or maybe just `Blockfrost` to avoid name clashes) with instance that can possibly call the fixed `mtl` client functions. What I'm not sure about is `ReaderT` containing `Project`, maybe we can just wrap our old `BlockfrostClient` type though. I'll play with it a bit!

**Comment by sorki** [comment]
Hi, I've opened #11 which adds [`MonadBlockfrost` class](https://github.com/blockfrost/blockfrost-haskell/pull/11/files#diff-5a2ec5a836e277bce5e9f7c4d31b31b95e4b40631a16c35da1e7d9cbe5800720R59-R61) allowing you to use a custom monad instead of the default `BlockfrostClient`.

Using this I was able to compose it with example `TestapiM` like this:

```haskell
class Monad m => TestapiM m where
  mGetTest :: m Bool

sample :: (MonadBlockfrost m, TestapiM m) => m ()
sample = pure ()

type GlobalConfig = (Bool, ClientConfig)
type App = ReaderT GlobalConfig (ExceptT ClientError IO)

runApp :: ClientConfig -> App a -> IO (Either ClientError a)
runApp globalC = runExceptT . flip runReaderT (True, globalC)

instance TestapiM App where
  mGetTest = fst <$> ask

instance MonadBlockfrost App where
  liftBlockfrostClient act = getConf >>= \(env, _prj) -> 
    (liftIO $ runClientM act env)
  getConf = snd <$> ask

```
Would this work for you?
