### ISSUE TITLE
"block_time" missing from the AddressTransaction type

### ISSUE THREAD

**Issue by honungsburk** [blockfrost/blockfrost-haskell#13]
I noticed that [AddressTransaction](https://hackage.haskell.org/package/blockfrost-api-0.3.0.0/docs/Blockfrost-Types-Cardano-Addresses.html#t:AddressTransaction) is missing "block_time" from the [api docs](https://docs.blockfrost.io/#tag/Cardano-Addresses/paths/~1addresses~1{address}~1transactions/get).

**Comment by sorki** [comment]
Thank you! I have a fix in https://github.com/blockfrost/blockfrost-haskell/pull/14 which I'll release as `0.3.1` tomorrow.
