### ISSUE TITLE
Add missing class instances to the Slot type

### ISSUE THREAD

**Issue by honungsburk** [blockfrost/blockfrost-haskell#15]
From playing around with the API I found that `Slot` is missing some useful class instances: Ord, Enum, Real, and Integral. 

Here are example implementations:
```
instance Ord Blockfrost.Slot where
  compare (Blockfrost.Slot a) (Blockfrost.Slot b)
    | a < b = LT
    | a == b = EQ
    | otherwise = GT

instance Enum Blockfrost.Slot where
  toEnum = Blockfrost.Slot . toInteger
  fromEnum = fromIntegral . Blockfrost.unSlot

instance Real Blockfrost.Slot where
  toRational = toRational . Blockfrost.unSlot

instance Integral Blockfrost.Slot where
  toInteger = toInteger . Blockfrost.unSlot
  quotRem a b =
    let (l, r) = quotRem (Blockfrost.unSlot a) (Blockfrost.unSlot b)
     in (Blockfrost.Slot l, Blockfrost.Slot r)
```

**Comment by sorki** [comment]
I've added couple of derived Ord instances in https://github.com/blockfrost/blockfrost-haskell/pull/14/commits/3038b0697e4fc8cc577d24c77c2ad241d3056add

I will extend this further with Enum, Real and Integral. I think all of them can be derived.
