### ISSUE TITLE
Specifying count

### ISSUE THREAD

**Issue by nazrhom** [blockfrost/blockfrost-haskell#20]
I see that some API functions have a `'` variant which allows setting Ordering and Page. I don't see an option for Count (how many results are displayed on a page) although most endpoints that accept Page/Ordering also support that.

It would be nice to be able to specify that, I need to find out the tx that minted an asset and my approach was to use `getAssetHistory` with default ordering and take the first result, is there any other way to achieve this without having to get all the extra transactions as well?

**Comment by nazrhom** [comment]
Just noticed that `getAssetDetails` happens to contain that information.
I'll leave this open as it still might be useful to be able to specify that query parameter.

**Comment by sorki** [comment]
`Paged` has a `countPerPage` field, so if you construct `Paged` directly you can adjust Count as well.

```haskell
-- | Pagination parameters
data Paged = Paged
  { countPerPage :: Int -- ^ Count of results per page
  , pageNumber   :: Int -- ^ Page number
  } deriving (Eq, Ord, Show)
```

See also https://hackage.haskell.org/package/blockfrost-client-core/docs/Blockfrost-Client-Pagination.html

**Comment by sorki** [comment]
Or you can use `def` from `Data.Default`
```hs
countOne = def { countPerPage = 1 }
```

**Comment by nazrhom** [comment]
@sorki thanks I had completely missed that!
