### ISSUE TITLE
Orphaned `Arbitrary` instances are brought into scope by the `Blockfrost.Client`

### ISSUE THREAD

**Issue by Unisay** [blockfrost/blockfrost-haskell#35]
**Actual situation**

Fact 1:
The [quickcheck-instances](https://hackage.haskell.org/package/quickcheck-instances) library has this warning in its documentation:

> Since all of these instances are provided as orphans, I recommend that you do not use this library within another library module, so that you don't impose these instances on down-stream consumers of your code.

Fact 2:
Blockfrost API library [uses](https://github.com/blockfrost/blockfrost-haskell/search?l=Cabal+Config&q=quickcheck-instances) `quickcheck-instances`

Fact 3:
`blockfrost-api` is a library that ignores the warning and causes problems associated with the orphaned instances to its users, even transitively, via the `blockfrost-client` dependency. 

**Desired situation**

`blockfrost-api` doesn't bring orphaned instances to scope for all its downstream users.

**Comment by sorki** [comment]
Published on Hackage as blockfrost-api 0.8.0.0 and blockfrost-client 0.7.1.1 that allows api 0.8.
