### ISSUE TITLE
Add query by payment credential

### ISSUE THREAD

**Issue by j-mueller** [blockfrost/blockfrost-haskell#68]
There's an [addressUtxos](https://github.com/blockfrost/blockfrost-haskell/blob/master/blockfrost-api/src/Blockfrost/API/Cardano/Addresses.hs#L39) query to get the UTxOs at a specific address. But I don't care about the stake credential (2nd part of the address), I just want to get all UTxOs that are locked by the same payment credential (1st part). This is not possible in the current API.

Issue #37  sounds related, but the fix did not actually add the "utxos by payment credential" route.

**Comment by j-mueller** [comment]
Ping

**Comment by sorki** [comment]
Ah, sorry I didn't notice the issue. This is actually supported by the API - it will try to parse both address and payment credential and automatically fallback to the latter if address can't be parsed completely. 

Just not documented or reflected here. 

We can either add the `addressUtxoByPaymentCred`, change the `Capture "address" Address` param to `Either Address PaymentCred` which would be just a different newtype to distinguish the two (but a breaking change) or ~~do nothing~~ just document this.

**Comment by j-mueller** [comment]
@sorki : How should I encode the payment credential? I tried just CBOR encoding it in hex representation but this gets rejected with a 400 error.

**Comment by sorki** [comment]
> [@sorki](https://github.com/sorki) : How should I encode the payment credential? I tried just CBOR encoding it in hex representation but this gets rejected with a 400 error.

Looks like it's bech32 encoded with a prefix, for example `addr_vkh15ew2tzjwn364l2pszu7j5h9w63v2crrnl97m074w9elrk6zy2tc`

https://cardano-mainnet.blockfrost.io/api/v0/addresses/addr_vkh15ew2tzjwn364l2pszu7j5h9w63v2crrnl97m074w9elrk6zy2tc/utxos

For reference here's the decoding function https://github.com/blockfrost/blockfrost-utils/blob/master/src/validation.ts#L109-L128

**Comment by j-mueller** [comment]
Got this to work using a custom bech32 instance for some of the types from `cardano-api` (see this [PR](https://github.com/j-mueller/sc-tools/pull/241/files#diff-2ff11c62bd10f6f407b149297f14c9b51e8564bd9587e0e338ab6f989b39b0d7R123-R141)).

Thanks!
